version: '3.8'

services:
  db:
    image: postgres:13
    container_name: fusionpbx_db
    environment:
      POSTGRES_USER: fusionpbx
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: fusionpbx
    volumes:
      - db_data:/var/lib/postgresql/data

  fusionpbx_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fusionpbx_web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  db_data:
